name: Auto release
on:
  push:
    branches:
      - master

jobs:
  Auto-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Auto release
        run: |
          yarn install
          yarn build
          cp -r ./build/* ./electron
          cd electron
          dir
          npm install
          npm run make
          cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
      - uses: actions/upload-artifact@v2
        with:
          name: electron
          path: electron/out/
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
